// pages/newsletter.js
import { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";

export default function Newsletter() {
  const [newsletter, setNewsletter] = useState(null);
  const [marketData, setMarketData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch("/api/newsletter").then(r => r.json()).then(d => {
      if (d.error) throw new Error(d.error);
      setNewsletter(d.newsletter); setMarketData(d.marketData || []);
    }).catch(e => setError(e.message)).finally(() => setLoading(false));
  }, []);

  const sentimentColor = newsletter?.sentiment==="bullish"?"#22c55e":newsletter?.sentiment==="bearish"?"#ef4444":"#f59e0b";
  const riskColor = newsletter?.riskLevel==="low"?"#22c55e":newsletter?.riskLevel==="high"?"#ef4444":"#f59e0b";

  return (
    <>
      <Head>
        <title>Daily Market Briefing — StockSage Pro</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet" />
      </Head>
      <main className="main">
        <div className="nl-nav">
          <Link href="/" className="back-link">← Back to StockSage</Link>
          <span className="nl-badge">📰 Daily Briefing</span>
        </div>
        {loading && <div className="loading-state"><div className="loading-orb" /><div className="loading-text">Generating today's market briefing...</div></div>}
        {error && <div className="error-box"><span>⚠</span><div>{error}</div></div>}
        {newsletter && !loading && (
          <div className="nl-container">
            <div className="nl-header">
              <div className="nl-date">{newsletter.date}</div>
              <h1 className="nl-headline">{newsletter.headline}</h1>
              <div className="nl-meta">
                <span className="nl-sentiment" style={{background:sentimentColor}}>{newsletter.sentiment==="bullish"?"🐂":newsletter.sentiment==="bearish"?"🐻":"😐"} {newsletter.sentiment?.toUpperCase()}</span>
                <span className="nl-risk" style={{borderColor:riskColor,color:riskColor}}>⚡ {newsletter.riskLevel?.toUpperCase()} RISK</span>
              </div>
            </div>
            {marketData.length > 0 && (
              <div className="nl-ticker-bar">
                {marketData.map((m,i) => (
                  <div key={i} className="nl-ticker-item">
                    <span className="nl-ticker-sym">{m.ticker}</span>
                    <span className="nl-ticker-price">${m.price}</span>
                    <span className={`nl-ticker-change ${parseFloat(m.change)>=0?"up":"down"}`}>{parseFloat(m.change)>=0?"▲":"▼"} {m.changePercent}</span>
                  </div>
                ))}
              </div>
            )}
            <div className="nl-opening">
              <div className="nl-opening-label">🔔 Opening Bell</div>
              <p className="nl-opening-text">{newsletter.openingBell}</p>
            </div>
            <div className="nl-sections">
              {newsletter.sections?.map((s,i) => (
                <div key={i} className="nl-section">
                  <div className="nl-section-title">{s.title}</div>
                  <p className="nl-section-content">{s.content}</p>
                </div>
              ))}
            </div>
            <div className="nl-risk-note" style={{borderColor:riskColor}}><span style={{color:riskColor}}>⚠️ Risk:</span> {newsletter.riskNote}</div>
            <div className="nl-cta"><Link href="/" className="nl-cta-btn">Analyze a Market →</Link></div>
            <p className="nl-disclaimer">Educational purposes only. Generated by AI using live data.</p>
          </div>
        )}
      </main>
    </>
  );
}
